%%%%%%------------------逆谐波均值滤波器--------------------------------
clc;
clear;
%读入图像，并转换为double型
I=imread('月光宝盒.bmp');
I=rgb2gray(I);%得到灰度图像
I_D=im2double(I);
I_D=imnoise(I_D,'gaussian',0.3);
[MM,NN]=size(I_D);
%定义子窗口的尺寸
m=3;
n=3;
%确定要扩展的行列数
len_m=floor(m/2);
len_n=floor(n/2);
%将原始图像进行扩展，这里采用了镜像扩展，以进行图像边缘计算
I_D_pad=padarray(I_D,[len_m,len_n],'symmetric');
%获得扩展后的图像尺寸
[M,N]=size(I_D_pad);
%滤波器阶数
Q=1.5;
J_Contraharmonic=zeros(MM,NN);
%逐点计算子窗口的谐波平均
for i=1+len_m:M-len_m
    for j=1+len_n:N-len_n
        %从扩展图像中取出子图像
        Block=I_D_pad(i-len_m:i+len_m,j-len_n:j+len_n);
        %求子窗口的谐波平均
        s1=sum(sum(Block.^(Q+1)));
        s2=sum(sum(Block.^Q));
        J_Contraharmonic(i-len_m,j-len_n)=s1/s2;
    end
end
imshow(J_Contraharmonic);
title('逆谐波均值滤波器');
